version: '1.24.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD : password
    ports:
      - 5435:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
     - 8082:8080